version: '3.7'

services:
  outrun-db:
    image: outrun-db
    container_name: outrun-db
    restart: always
    ports:
      - ${MONGO_INITDB_PORT}:${MONGO_INITDB_PORT}
    volumes:
      - mongo:/data/db
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_INITDB_APP_USERNAME: ${MONGO_INITDB_APP_USERNAME}
      MONGO_INITDB_APP_PASSWORD: ${MONGO_INITDB_APP_PASSWORD}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

  outrun:
    image: outrun
    container_name: outrun
    restart: always
    ports:
      - ${OUTRUN_CORE_PORT}:${OUTRUN_CORE_PORT}
    environment:
      SERVER_PORT: ${OUTRUN_CORE_PORT}
    depends_on:
      - outrun-db

#  outrun-web:
#    image: outrun-web
#    container_name: outrun-web
#    restart: always
#    ports:
#      - ${OUTRUN_WEB_PORT}:${OUTRUN_WEB_PORT}
#    environment:
#      SERVER_PORT: ${OUTRUN_WEB_PORT}
#    depends_on:
#      - outrun-db
#      - outrun

volumes:
  mongo: