version: '3.7'

services:
  outrun-db:
#    image: 725705545716.dkr.ecr.eu-west-2.amazonaws.com/outrun-db:latest
    image: outrun-db
    container_name: outrun-db
    restart: always
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}
    expose:
      - ${MYSQL_PORT}
    volumes:
      - outrun:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MONGO_INITDB_APP_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  outrun:
    image: 725705545716.dkr.ecr.eu-west-2.amazonaws.com/outrun:latest
#    image: outrun
    container_name: outrun
    restart: always
    ports:
      - ${OUTRUN_CORE_PORT}:${OUTRUN_CORE_PORT}
    environment:
      SERVER_PORT: ${OUTRUN_CORE_PORT}
    depends_on:
      - outrun-db

  outrun-web:
    image: 725705545716.dkr.ecr.eu-west-2.amazonaws.com/outrun-web:latest
#    image: outrun-web
    container_name: outrun-web
    restart: always
    ports:
      - ${OUTRUN_WEB_PORT}:${OUTRUN_WEB_PORT}
    environment:
      SERVER_PORT: ${OUTRUN_WEB_PORT}
    depends_on:
      - outrun-db
      - outrun

volumes:
  outrun-: